# Generated by Django 4.2 on 2023-05-02 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('confirmPassword', models.CharField(max_length=50, verbose_name='Повторите пароль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
