services:
  01_frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - NODE_ENV=development
    command: npm run dev 
    depends_on:
      - 01_backend
    
  01_backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - DB_HOST=data_base
      - DB_NAME=LH_base
      - DB_USER=admin
      - DB_PASS=root
    command: >
      sh -c "sleep 15 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - data_base
  

  data_base:
    image: postgres:14.6-alpine
    ports:
      - "5432:5432"
    container_name: LH_DB
    environment:
      - POSTGRES_DB=LH_base
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.command
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"


  # 01_frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.front
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/frontend
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run dev
  #   # depends_on:
  #   #   - 01_backend
    
    
  

  
    


