<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-06-02 09:04
=======
# Generated by Django 4.2.1 on 2023-06-01 13:02
>>>>>>> ea5f5dcfa1d0ff6db8460176b3f2bbe4884164a4

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='номером телефона'),
        ),
    ]
